version: "3.7"

networks:
  traefik_web-network:
    external: true

services:
  web:
    image: ghcr.io/mastodon/mastodon:v4.2.1
    restart: unless-stopped
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - '3000:3000'
    volumes:
      - ./public/system:/mastodon/public/system
    networks:
      - traefik_web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mastodon.entrypoints=https"
      - "traefik.http.routers.mastodon.rule=Host(`mastodon.uqiantu.com`)"
      - "traefik.http.routers.mastodon.tls.certresolver=myresolver"
      - "traefik.http.routers.mastodon.service=mastodon"
      - "traefik.http.services.mastodon.loadbalancer.server.port=3000"

  streaming:
    image: ghcr.io/mastodon/mastodon:v4.2.1
    restart: unless-stopped
    env_file: .env.production
    command: node ./streaming
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - '4000:4000'
    networks:
      - traefik_web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mastodon-api.entrypoints=https"
      - "traefik.http.routers.mastodon-api.rule=Host(`mastodon.uqiantu.com`) && PathPrefix(`/api/v1/streaming`)"
      - "traefik.http.routers.mastodon-api.tls.certresolver=myresolver"
      - "traefik.http.routers.mastodon-api.service=mastodon-api"
      - "traefik.http.services.mastodon-api.loadbalancer.server.port=4000"

  sidekiq:
    image: ghcr.io/mastodon/mastodon:v4.2.1
    restart: unless-stopped
    env_file: .env.production
    command: bundle exec sidekiq
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    networks:
      - traefik_web-network

#  libretranslate:
#   image: libretranslate/libretranslate:v1.5.2
#   restart: unless-stopped
#   volumes:
#     - ./libretranslate:/home/libretranslate/.local
#   networks:
#     - traefik_web-network
#
#  es:
#   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
#   restart: unless-stopped
#   environment:
#     ES_JAVA_OPTS: -Xms512m -Xmx512m
#     cluster.name: es-mastodon
#     discovery.type: single-node
#     bootstrap.memory_lock: 'true'
#   volumes:
#     - ./es:/usr/share/elasticsearch/data
#   networks:
#     - traefik_web-network
#   ulimits:
#     memlock:
#       soft: -1
#       hard: -1