version: "3.7"

# 使用外部网络
# docker network create traefik_web-network
networks:
  traefik_web-network:
    external: true

services:
  ent:
    image: chudaozhe/ent:api1.0-release
    hostname: ent
    restart: unless-stopped
    tty: true
    volumes:
      - ./data:/data/data
      - ./logs:/data/logs
    labels:
      - "traefik.http.routers.ent.entrypoints=http"
      - "traefik.http.routers.ent.rule=Host(`ent.uqiantu.com`)"

      - "traefik.http.routers.ent-secure.entrypoints=https"
      - "traefik.http.routers.ent-secure.tls.certResolver=myresolver"
      - "traefik.http.routers.ent-secure.rule=Host(`ent.uqiantu.com`)"

      - "traefik.http.routers.ent-secure.service=ent-secure"
      - "traefik.http.services.ent-secure.loadbalancer.server.port=8097"
    networks:
      - traefik_web-network

  admin:
    image: chudaozhe/ent:admin1.0-release
    hostname: admin
    restart: unless-stopped
    tty: true
    labels:
      - "traefik.http.routers.admin.rule=Host(`ent.uqiantu.com`) && PathPrefix(`/console`)"
    networks:
      - traefik_web-network