version: "3.7"

# 使用外部网络
# docker network create traefik_web-network
networks:
  traefik_web-network:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:2.19.4
    command: -H unix:///var/run/docker.sock
#    ports:
#      - "8000:8000"
#      - "9443:9443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - traefik_web-network
    labels:
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.uqiantu.com`)"

      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.tls.certResolver=myresolver"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.uqiantu.com`)"

      - "traefik.http.routers.portainer-secure.service=portainer-secure"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"
