---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My Service Group:
    - Traefik:
        icon: traefik.png
        href: https://traefik.uqiantu.com
        description: Traefik is awesome
        server: my-docker
        container: traefik-reverse-proxy-1
        showStats: true
        siteMonitor: https://www.cuiwei.net
        widget:
          type: traefik
          url: https://traefik.uqiantu.com
          username: admin # optional
          password: admin # optional

    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.uqiantu.com
        description: qBittorrent is awesome
        server: my-docker
        container: qbittorrent
        showStats: true
        siteMonitor: https://www.cuiwei.net
        widget:
          type: qbittorrent
          url: https://qbittorrent.uqiantu.com
          username: admin
          password: 4scYaDXGI

    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.uqiantu.com
        description: Nextcloud is awesome
        server: my-docker
        container: docker-nextcloud
        showStats: true
        siteMonitor: https://www.cuiwei.net
        widget:
          type: nextcloud
          url: https://nextcloud.uqiantu.com
          username: admin2
          password: admin

    - Portainer:
        icon: portainer.png
        href: https://portainer.uqiantu.com
        description: Portainer is awesome
        server: my-docker
        container: portainer-portainer-1
        showStats: true
        siteMonitor: https://www.cuiwei.net
        widget:
          type: portainer
          url: https://portainer.uqiantu.com
          env: 1
          key: ptr_pgcYW68yszOIFULjWuhRywlnMsSQYgykXhgVvJRqLWM=
